[package]
name = "sklearn_rust"
version = "0.1.0"
authors = ["tushushu"]
edition = "2018"

[lib]
name = "sklearn_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16", features = ["extension-module"] }
numpy = "0.16"

[package.metadata.maturin]
python-source = "python"
