name: Unit Tests

on:
  pull_request:
  release:
    types: [published]

  workflow_dispatch:


jobs:
  pytest:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - name: Install Python packages
        run: |
          pip install -r ./requirements/dev.txt
      - name: Build sklearn_prod
        run: |
          maturin build --out dist -m sklearn_prod/Cargo.toml
      - name: Install sklearn_prod
        run: |
          pip install sklearn_prod --no-index --find-links dist --force-reinstall 
      - name: Python UnitTest
        run: |
          cd tests
          pytest ../tests